variables:
  ARTIFACTORY_ENABLED: "true"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  DONT_CACHE_LAST_RESPONSE: "true"

  GCS_MARKET_BUCKET: "marketplace-dist"
  GCS_MARKET_V2_BUCKET: "marketplace-v2-dist"
  GCS_MARKET_XPANSE_BUCKET: "xpanse-dist"
  GCS_MARKET_XSOAR_SAAS_BUCKET: "marketplace-saas-dist"
  GCS_MARKET_PLATFORM_BUCKET: "marketplace-cortex-content-dev/april-content"  # Platform Internal production bucket. April version CIAC-13208.

  GCS_MARKET_BUCKET_DEV: "marketplace-dist-dev"
  GCS_MARKET_V2_BUCKET_DEV: "marketplace-v2-dist-dev"
  GCS_MARKET_XSOAR_SAAS_BUCKET_DEV: "marketplace-saas-dist-dev"
  GCS_MARKET_PLATFORM_BUCKET_DEV: "marketplace-cortex-content-build/content-dev"

  STORAGE_BASE_PATH: ""
  SLACK_CHANNEL: "dmst-build-test"
  SLACK_PARENT_PIPELINE_ID: ""  # empty string, no parent pipeline.
  SLACK_PARENT_PROJECT_ID: ""  # empty string, no parent project.
  DEMISTO_README_VALIDATION: "true"
  ARTIFACTS_FOLDER: "${CI_PROJECT_DIR}/artifacts"
  PIPELINE_JOBS_FOLDER: "${CI_PROJECT_DIR}/pipeline_jobs_folder"
  ARTIFACTS_FOLDER_XSOAR: "${CI_PROJECT_DIR}/artifacts/xsoar"  # Used for both XSOAR on-prem and XSOAR SaaS
  ARTIFACTS_FOLDER_MPV2: "${CI_PROJECT_DIR}/artifacts/marketplacev2"
  ARTIFACTS_FOLDER_XPANSE: "${CI_PROJECT_DIR}/artifacts/xpanse"
  ARTIFACTS_FOLDER_PLATFORM: "${CI_PROJECT_DIR}/artifacts/platform"

  JIRA_ISSUE_UNRESOLVED_TRANSITION_NAME: "Backlog"
  JIRA_PROJECT_ID: "CIAC"
  JIRA_VERIFY_SSL: "True"
  # Jira additional fields are a json string that will be parsed into a dictionary containing the name of the field as the key and the value as a dictionary containing the value of the field.
  JIRA_ADDITIONAL_FIELDS: '{"customfield_19581":{"value": "IN"},"customfield_19582":{"value": "FALSE"},"customfield_19583":{"value": "Single"}}'
  BASH_ENV: "${CI_PROJECT_DIR}/artifacts/bash_env"
  PYTHONPATH: "${CI_PROJECT_DIR}"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  FEATURE_BRANCH_NAME: "v4.5.0"
  IFRA_ENV_TYPE: "Content-Env"
  GET_SOURCES_ATTEMPTS: 3  # see https://docs.gitlab.com/ee/ci/runners/configure_runners.html#job-stages-attempts

  GCS_BUILD_BUCKET: "marketplace-ci-build-xsoar-dev"
  GCS_BUILD_V2_BUCKET: "marketplace-ci-build-v2-dev"
  GCS_BUILD_XPANSE_BUCKET: "marketplace-ci-build-xpanse-dev"
  GCS_BUILD_XSOAR_SAAS_BUCKET: "marketplace-ci-build-xsoar-saas-dev"
  GCS_BUILD_PLATFORM_BUCKET: "marketplace-cortex-content-build"

  GCS_PRODUCTION_BUCKET: "marketplace-dist"
  GCS_PRODUCTION_V2_BUCKET: "marketplace-v2-dist"
  GCS_PRODUCTION_XPANSE_BUCKET: "xpanse-dist"
  GCS_PRODUCTION_XSOAR_SAAS_BUCKET: "marketplace-saas-dist"
  GCS_INTERNAL_PRODUCTION_PLATFORM_BUCKET: "marketplace-cortex-content-dev/april-content" # Platform Internal production bucket. April version CIAC-13208.

  GCS_EXTERNAL_PLATFORM_BUCKET_PROD_US: "marketplace-cortex-content-prod-us/april-content"

  DEMISTO_CONNECTION_POOL_MAXSIZE: "180" # see this issue for more info https://github.com/demisto/etc/issues/36886
  DEMISTO_SDK_NIGHTLY: "false"
  IS_NIGHTLY: "false"
  IS_NATIVE_NIGHTLY: "false"
  SCHEDULED_NIGHTLY: "false" # true only during a real scheduled nightly run.
  OLD_NIGHTLY: "false"
  SDK_REF: "master" # The SDK reference to use when OVERRIDE_SDK_REF is "true".
  OVERRIDE_SDK_REF: "false" # Whether to override the SDK ref defined in pyproject.toml, with the one defined in SDK_REF.
  OVERRIDE_ALL_PACKS: "false"
  TEST_UPLOAD: "true"
  FORCE_BUCKET_UPLOAD: "false"
  BUCKET_UPLOAD: "false"
  NATIVE_CANDIDATE_IMAGE: "latest"
  DEMISTO_SDK_LOG_FILE_PATH: "${ARTIFACTS_FOLDER}/logs"
  CONTENT_GITLAB_CI: "true"
  POETRY_VIRTUALENVS_OPTIONS_ALWAYS_COPY: "true"
  FF_USE_FASTZIP: "true"
  POETRY_VERSION: "1.8.2"
  INSTALL_POETRY: "true"
  DOCKER_IO: "docker.io" # defined in the project level CI/CD variables
  RESET_CORE_PACK_VERSION: "true"
  IS_AUD_FLOW:
    description: "Whether we are running in Auto update docker flow or not."
    value: "false"
    options:
      - "true"
      - "false"
  DRY_RUN:
    description: "Whether to deploy the files into the dev buckets (true) or the proud ones (false).
     Used in override-corepacks and deploy-auto-upgrade-packs flows. Default value is false."
    value: "false"
    options:
      - "true"
      - "false"
  PERMISSION_GROUP:
    description: "Specify the user group to be searched for when determining the permissions for a specific user."
    value: "content-leaders"
    options:
      - "content-leaders"
      - "content-research"