default:
  image: ${DOCKER_IO}/devdemisto/gitlab-content-ci:1.0.0.2485751
  artifacts:
    expire_in: 30 days
    paths:
      - ${CI_PROJECT_DIR}/artifacts/*
      - ${CI_PROJECT_DIR}/pipeline_jobs_folder/*
    when: always

stages:
  - notify

include:
  - file: .gitlab/ci/content-ci/ci/.gitlab-ci.variables.yml
    ref: $INFRA_BRANCH
    project: "${CI_PROJECT_NAMESPACE}/infra"
  - file: .gitlab/ci/content-ci/ci/.gitlab-ci.global.yml
    ref: $INFRA_BRANCH
    project: "${CI_PROJECT_NAMESPACE}/infra"

slack-notify:
  tags:
    - gke
  stage: notify
  extends: .default-job-settings
  script:
    - python3 ./Tests/scripts/gitlab_slack_notifier.py -p "${PIPELINE_TO_QUERY}" -s "${SLACK_TOKEN}" -c "${GITLAB_STATUS_TOKEN}" -ch "${SLACK_CHANNEL}" --triggering-workflow "${WORKFLOW}" --allow-failure "${SLACK_ALLOW_FAILURE}" --name-mapping_path "${CI_PROJECT_DIR}/config/name_mapping.json" --dry_run "${DRY_RUN}"
  retry:
    max: 2
  needs:
    - pipeline: $PIPELINE_TO_QUERY
      job: $JOB_NAME
  variables:
    DRY_RUN: $DRY_RUN
